# Generated by Django 4.2.5 on 2023-09-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item',
            field=models.ManyToManyField(related_name='menu_items', to='products.menu'),
        ),
    ]
