# Generated by Django 4.2.5 on 2023-10-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': 'Order', 'verbose_name_plural': 'الاوردرات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'عناصر الاوردر'},
        ),
    ]
