# Generated by Django 4.2.5 on 2023-11-01 08:03

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[products.validators.validate_price], verbose_name='سعر التوصيل'),
        ),
    ]
