# Generated by Django 4.2.5 on 2023-09-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_menu_item_orderitem_menu_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menu_item',
            new_name='order_items',
        ),
    ]
