# Generated by Django 4.2.5 on 2023-09-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_menu_item_orderitem_order_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_items',
            new_name='menu_item',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
