# Generated by Django 4.2.5 on 2023-09-25 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت الدخول')),
                ('out_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الخروج')),
                ('employee_attended', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendance', to='employees.employee', verbose_name='الموظف')),
                ('user_created_the_attendence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created', to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
            ],
            options={
                'verbose_name_plural': 'الحضور والانصراف',
                'db_table': 'الحضور والانصراف',
                'ordering': ['-id'],
            },
        ),
    ]
