# Generated by Django 4.2.5 on 2023-09-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت الدخول')),
                ('out_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الخروج')),
            ],
            options={
                'verbose_name_plural': 'attendances',
                'db_table': 'Attendance',
            },
        ),
    ]
