# Generated by Django 4.2.5 on 2023-09-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'الحضور والانصراف'},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='user_created_the_attendence',
            new_name='user_created_the_attendance',
        ),
        migrations.AlterModelTable(
            name='attendance',
            table=None,
        ),
    ]
