# Generated by Django 4.2.5 on 2023-09-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendance',
            table='Attendance',
        ),
    ]
