# Generated by Django 4.2.5 on 2023-09-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'الحضور والانصراف'},
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='الحضور والانصراف',
        ),
    ]
