# Generated by Django 4.2.5 on 2023-09-30 20:41

import customers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20, null=True, unique=True, validators=[customers.validators.valid_phone_number]),
        ),
    ]
