<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-10-05 16:24
=======
# Generated by Django 4.2.5 on 2023-10-08 07:43
>>>>>>> f7215295e1727762a1d33999583635936d4dfb5a

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='related_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shift', verbose_name='الشيفت المرتبط'),
        ),
    ]
