# Generated by Django 4.2.5 on 2023-09-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='type',
            field=models.TextField(choices=[('سلفه', 'Advance Payment'), ('تكلفه', 'Normal Cost')], default='تكلفه'),
        ),
    ]
