# Generated by Django 4.2.5 on 2023-09-29 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_alter_shiftreport_net_profit_and_more'),
        ('financials', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='related_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.shift', verbose_name='الشيفت المرتبط'),
        ),
    ]
