# Generated by Django 4.2.5 on 2023-10-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت الدفع'),
        ),
    ]
