# Generated by Django 4.2.5 on 2023-10-31 06:04

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLogEntry',
            fields=[
            ],
            options={
                'verbose_name': 'اخر حدث',
                'verbose_name_plural': 'الاحداث الاخيرة',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin.logentry',),
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
