# Generated by Django 4.2.5 on 2023-09-25 17:14

from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[products.validators.validate_price], verbose_name='price')),
                ('available', models.BooleanField(default=True, verbose_name='is_available')),
                ('category', models.TextField(choices=[('food', 'Food'), ('Drinks', 'drinks')], default='Drinks', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'menu items',
                'db_table': 'menu items',
                'ordering': ['-id'],
            },
        ),
    ]
