# Generated by Django 4.2.5 on 2023-09-26 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='menu_items',
        ),
    ]
