# Generated by Django 4.2.5 on 2023-09-24 00:52

from django.db import migrations, models
import employees.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[employees.validators.valid_salary]),
        ),
    ]
