# Generated by Django 4.2.5 on 2023-10-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShiftReport',
        ),
    ]
