# Generated by Django 4.2.5 on 2023-09-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftreport',
            name='net_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='صافي الربح'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='total_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='اجمالي التكلفة'),
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='total_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='اجمالي الربح'),
        ),
    ]
