# Generated by Django 4.2.5 on 2023-09-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftreport',
            name='total_costs',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='total costs'),
        ),
    ]
