# Generated by Django 4.2.5 on 2023-09-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_alter_shiftreport_net_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftreport',
            name='time_duration',
        ),
        migrations.AlterField(
            model_name='shiftreport',
            name='related_shift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='shifts.shift', verbose_name='الشيفت'),
        ),
    ]
