# Generated by Django 4.2.5 on 2023-10-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('tax', models.PositiveIntegerField(blank=True, null=True, verbose_name='tax')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'الدليفري',
                'db_table': 'deliveries',
                'ordering': ['-id'],
            },
        ),
    ]
