# Generated by Django 4.2.5 on 2023-09-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_delivered_alter_delivery_on_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
