# Generated by Django 4.2.5 on 2023-09-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_delivery_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='on_order',
            new_name='for_order',
        ),
    ]
