# Generated by Django 4.2.5 on 2023-10-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('customers', '0002_customer_address'),
        ('deliveries', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='name',
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_delivery', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='for_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_deliveries', to='orders.order'),
            preserve_default=False,
        ),
    ]
