# Generated by Django 4.2.5 on 2023-10-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_remove_delivery_name_delivery_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-id'], 'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelTable(
            name='delivery',
            table='deliveries',
        ),
    ]
