# Generated by Django 4.2.5 on 2023-11-01 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ajenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajenda',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول'),
        ),
    ]
